### ISSUE TITLE
SimpleScreenRecorder appears to be missing i386 libraries

### ISSUE THREAD

**Issue by egee-irl** [ProfessorKaos64/SteamOS-Tools#96]
It would appear that the version of SimpleScreenRecorder currently in the repo only provides the 64bit version of the application and libraries. This makes recording 32bit applications somewhat difficult.

I haven't been able to confirm 100% but it appears that the GLInject library is also missing, which means recording the OpenGL output is impossible - http://www.maartenbaert.be/simplescreenrecorder/recording-steam-games/

**Comment by ProfessorKaos64** [comment]
Like with obs-studio, i'll debinize this one with a proper setup. I'll reply when it's repackaged.

**Comment by ProfessorKaos64** [comment]
The below packages are now live. Please update and retest when time allows.

simplescreenrecorder-lib_0.3.6+git+SteamOS2_amd64.deb
simplescreenrecorder_0.3.6+git+SteamOS2_amd64.deb

**Comment by egee-irl** [comment]
More dependencies! Looks like libstdc++ was needed before GLInject would be happy. Might have been others but that's the one that barked at me.

**Comment by ProfessorKaos64** [comment]
hmm, that isn't noted in the control file. Do you want me to include that in the control file as a build dependency for you to try again? Do you know which [version](https://packages.debian.org/search?suite=jessie&keywords=libstdc%2B%2B)? Latest?

**Comment by egee-irl** [comment]
Actually, have a look at this - this is the error message:

/bin/bash: /home/desktop/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libssr-glinject.so)

**Comment by ProfessorKaos64** [comment]
libstdc++6 should solve that. If you install it, does it work? Or is it needed before build time as a build-dep?

**Comment by egee-irl** [comment]
I've got both libstdc+6 and :i386 installed and it still doesn't like it. I appears to dislike the version that is packaged in the Steam Runtime, which is odd.

**Comment by ProfessorKaos64** [comment]
Do you have the gcc base files by any chance? , e.g. gcc-4.9-base

**Comment by egee-irl** [comment]
Indeed, also 4.9:i386

**Comment by ProfessorKaos64** [comment]
See: https://github.com/MaartenBaert/ssr/issues/214

**Comment by egee-irl** [comment]
Doing simplescreenrecorder:i386 or simplescreenrecorder-lib:i386 yields nothing

**Comment by egee-irl** [comment]
Issue appears to be upstream with SSR. I'll go ahead and close this one. We're done here ;)
